enableGlobalCache: false

enableScripts: false

enableTelemetry: true

npmAuditIgnoreAdvisories:
  - "whatwg-encoding (deprecation)"
  - "glob (deprecation)"
  - "1112455"
  - "1112453"
  - "1113416"
  - "1113418"
  - "1113419"
  - "1113555"

supportedArchitectures:
  cpu:
    - x64
  libc:
    - musl
    - glibc
  os:
    - linux
    - win32
    - darwin

yarnPath: .yarn/releases/yarn-4.9.1.cjs
