enableGlobalCache: false

enableScripts: false

enableTelemetry: true

npmAuditIgnoreAdvisories:
  - "whatwg-encoding (deprecation)"
  - "glob (deprecation)"
  - "1112455"
  - "1112453"
  - "1113302"
  - "1113303"
  - "1113321"
  - "1113371"

supportedArchitectures:
  cpu:
    - x64
  libc:
    - musl
    - glibc
  os:
    - linux
    - win32
    - darwin

yarnPath: .yarn/releases/yarn-4.9.1.cjs
