enableGlobalCache: false

npmAuditIgnoreAdvisories:
  - 1105422 # brace-expansion CVE-2025-5889 https://github.com/advisories/GHSA-v6h2-p8h4-qcjw

supportedArchitectures:
  cpu:
    - x64
  libc:
    - musl
    - glibc
  os:
    - linux
    - win32
    - darwin

yarnPath: .yarn/releases/yarn-4.9.1.cjs
