enableGlobalCache: false

enableScripts: false

enableTelemetry: true

npmAuditIgnoreAdvisories:
  - "whatwg-encoding (deprecation)"

supportedArchitectures:
  cpu:
    - x64
  libc:
    - musl
    - glibc
  os:
    - linux
    - win32
    - darwin

yarnPath: .yarn/releases/yarn-4.9.1.cjs
