/*
 * Copyright (C) 2004-2009  exedio GmbH (www.exedio.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package com.exedio.cope.console.example;

import com.exedio.cope.Item;
import com.exedio.cope.pattern.Hash;
import com.exedio.cope.pattern.MessageDigestAlgorithm;
import com.exedio.cope.pattern.MessageDigestHash;

public final class AHashItem extends Item
{
	static final Hash md8 = new MessageDigestHash(8);
	static final Hash md8x6latin = new MessageDigestHash(80000, "ISO-8859-1");
	static final Hash md5 = new Hash(new MessageDigestAlgorithm("MD5", 2, 5000));
	static final Hash deterministic = new Hash(new MessageDigestAlgorithm("MD5", 0, 1));

	/**

	 **
	 * Creates a new AHashItem with all the fields initially needed.
	 * @param md8 the initial value for field {@link #md8}.
	 * @param md8x6latin the initial value for field {@link #md8x6latin}.
	 * @param md5 the initial value for field {@link #md5}.
	 * @param deterministic the initial value for field {@link #deterministic}.
	 * @throws com.exedio.cope.MandatoryViolationException if md8, md8x6latin, md5, deterministic is null.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tags <tt>@cope.constructor public|package|protected|private|none</tt> in the class comment and <tt>@cope.initial</tt> in the comment of fields.
	 */
	AHashItem(
				final java.lang.String md8,
				final java.lang.String md8x6latin,
				final java.lang.String md5,
				final java.lang.String deterministic)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		this(new com.exedio.cope.SetValue<?>[]{
			AHashItem.md8.map(md8),
			AHashItem.md8x6latin.map(md8x6latin),
			AHashItem.md5.map(md5),
			AHashItem.deterministic.map(deterministic),
		});
	}/**

	 **
	 * Creates a new AHashItem and sets the given fields initially.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.generic.constructor public|package|protected|private|none</tt> in the class comment.
	 */
	private AHashItem(final com.exedio.cope.SetValue<?>... setValues)
	{
		super(setValues);
	}/**

	 **
	 * Returns whether the given value corresponds to the hash in {@link #md8}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.check public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final boolean checkMd8(final java.lang.String md8)
	{
		return AHashItem.md8.check(this,md8);
	}/**

	 **
	 * Wastes (almost) as much cpu cycles, as a call to <tt>checkMd8</tt> would have needed.
	 * Needed to prevent Timing Attacks.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.blind public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	static final void blindMd8(final java.lang.String md8)
	{
		AHashItem.md8.blind(md8);
	}/**

	 **
	 * Sets a new value for {@link #md8}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setMd8(final java.lang.String md8)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		AHashItem.md8.set(this,md8);
	}/**

	 **
	 * Returns the encoded hash value for hash {@link #md8}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getSHA512s8i8 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getMd8SHA512s8i8()
	{
		return AHashItem.md8.getHash(this);
	}/**

	 **
	 * Sets the encoded hash value for hash {@link #md8}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setSHA512s8i8 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setMd8SHA512s8i8(final java.lang.String md8)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		AHashItem.md8.setHash(this,md8);
	}/**

	 **
	 * Returns whether the given value corresponds to the hash in {@link #md8x6latin}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.check public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final boolean checkMd8x6latin(final java.lang.String md8x6latin)
	{
		return AHashItem.md8x6latin.check(this,md8x6latin);
	}/**

	 **
	 * Wastes (almost) as much cpu cycles, as a call to <tt>checkMd8x6latin</tt> would have needed.
	 * Needed to prevent Timing Attacks.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.blind public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	static final void blindMd8x6latin(final java.lang.String md8x6latin)
	{
		AHashItem.md8x6latin.blind(md8x6latin);
	}/**

	 **
	 * Sets a new value for {@link #md8x6latin}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setMd8x6latin(final java.lang.String md8x6latin)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		AHashItem.md8x6latin.set(this,md8x6latin);
	}/**

	 **
	 * Returns the encoded hash value for hash {@link #md8x6latin}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getSHA512s8i80000 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getMd8x6latinSHA512s8i80000()
	{
		return AHashItem.md8x6latin.getHash(this);
	}/**

	 **
	 * Sets the encoded hash value for hash {@link #md8x6latin}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setSHA512s8i80000 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setMd8x6latinSHA512s8i80000(final java.lang.String md8x6latin)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		AHashItem.md8x6latin.setHash(this,md8x6latin);
	}/**

	 **
	 * Returns whether the given value corresponds to the hash in {@link #md5}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.check public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final boolean checkMd5(final java.lang.String md5)
	{
		return AHashItem.md5.check(this,md5);
	}/**

	 **
	 * Wastes (almost) as much cpu cycles, as a call to <tt>checkMd5</tt> would have needed.
	 * Needed to prevent Timing Attacks.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.blind public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	static final void blindMd5(final java.lang.String md5)
	{
		AHashItem.md5.blind(md5);
	}/**

	 **
	 * Sets a new value for {@link #md5}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setMd5(final java.lang.String md5)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		AHashItem.md5.set(this,md5);
	}/**

	 **
	 * Returns the encoded hash value for hash {@link #md5}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getMD5s2i5000 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getMd5MD5s2i5000()
	{
		return AHashItem.md5.getHash(this);
	}/**

	 **
	 * Sets the encoded hash value for hash {@link #md5}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setMD5s2i5000 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setMd5MD5s2i5000(final java.lang.String md5)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		AHashItem.md5.setHash(this,md5);
	}/**

	 **
	 * Returns whether the given value corresponds to the hash in {@link #deterministic}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.check public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final boolean checkDeterministic(final java.lang.String deterministic)
	{
		return AHashItem.deterministic.check(this,deterministic);
	}/**

	 **
	 * Wastes (almost) as much cpu cycles, as a call to <tt>checkDeterministic</tt> would have needed.
	 * Needed to prevent Timing Attacks.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.blind public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	static final void blindDeterministic(final java.lang.String deterministic)
	{
		AHashItem.deterministic.blind(deterministic);
	}/**

	 **
	 * Sets a new value for {@link #deterministic}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.set public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setDeterministic(final java.lang.String deterministic)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		AHashItem.deterministic.set(this,deterministic);
	}/**

	 **
	 * Returns the encoded hash value for hash {@link #deterministic}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.getMD5 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final java.lang.String getDeterministicMD5()
	{
		return AHashItem.deterministic.getHash(this);
	}/**

	 **
	 * Sets the encoded hash value for hash {@link #deterministic}.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.setMD5 public|package|protected|private|none|non-final</tt> in the comment of the field.
	 */
	final void setDeterministicMD5(final java.lang.String deterministic)
			throws
				com.exedio.cope.MandatoryViolationException
	{
		AHashItem.deterministic.setHash(this,deterministic);
	}/**

	 **
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private static final long serialVersionUID = 1l;/**

	 **
	 * The persistent type information for aHashItem.
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 *       It can be customized with the tag <tt>@cope.type public|package|protected|private|none</tt> in the class comment.
	 */
	public static final com.exedio.cope.Type<AHashItem> TYPE = com.exedio.cope.TypesBound.newType(AHashItem.class);/**

	 **
	 * Activation constructor. Used for internal purposes only.
	 * @see com.exedio.cope.Item#Item(com.exedio.cope.ActivationParameters)
	 * @cope.generated This feature has been generated by the cope instrumentor and will be overwritten by the build process.
	 */
	private AHashItem(final com.exedio.cope.ActivationParameters ap){super(ap);
}}
